// =============================================================================
// Brainoro OS — CBSE Authoritative NCERT Source Extractor
// Independent official TOC extractor & normalizer for NCERT textbooks.
// Decoupled from application DB to provide an authoritative independent oracle.
// =============================================================================

import {
  CbseSourceManifestEntry,
  OfficialExtractedTextbook,
  OfficialExtractedChapter,
} from '../types/cbseReconciliation';

/**
 * Normalizes title string formatting (whitespace, typographic dashes, smart quotes)
 * WITHOUT normalizing away meaningful educational differences (e.g. Roman numerals,
 * hyphenated part numbers like 'Proportional Reasoning-1' vs 'Proportional Reasoning-2').
 */
export function normalizeChapterTitle(raw: string): string {
  if (!raw) return '';
  return raw
    .trim()
    .replace(/[\u2018\u2019]/g, "'")       // smart single quotes
    .replace(/[\u201C\u201D]/g, '"')       // smart double quotes
    .replace(/[\u2013\u2014]/g, '-')       // en/em dashes to standard hyphen
    .replace(/\s+/g, ' ')                  // normalize consecutive spaces
    .replace(/\s*:\s*/g, ': ')             // standardized colon spacing
    .trim();
}

/**
 * Official Statutory NCERT Table-of-Contents Registry (Independent Oracle).
 * Sourced directly from official NCERT publications catalogue and ncert.nic.in/textbook.php.
 */
const STATUTORY_NCERT_ORACLE_TOC: Record<string, string[]> = {
  // --- CLASS 6 (NCF-SE 2024 Edition) ---
  femh1: [
    'Patterns in Mathematics',
    'Lines and Angles',
    'Number Play',
    'Data Handling and Presentation',
    'Prime Time',
    'Perimeter and Area',
    'Fractions',
    'Playing with Constructions',
    'Symmetry',
    'The Other Side of Zero',
  ],
  fecu1: [
    'The Wonderful World of Science',
    'Diversity in the Living World',
    'Mindful Eating: A Path to a Healthy Body',
    'Exploring Magnets',
    'Measurement of Length and Motion',
    'Materials Around Us',
    'Temperature and its Measurement',
    'A Journey through States of Water',
    'Methods of Separation in Everyday Life',
    'Living Creatures: Exploring their Characteristics',
    'Nature’s Treasures',
    'Beyond Earth',
  ],
  fesc1: [
    'The Wonderful World of Science',
    'Diversity in the Living World',
    'Mindful Eating: A Path to a Healthy Body',
    'Exploring Magnets',
    'Measurement of Length and Motion',
    'Materials Around Us',
    'Temperature and its Measurement',
    'A Journey through States of Water',
    'Methods of Separation in Everyday Life',
    'Living Creatures: Exploring their Characteristics',
    "Nature's Treasures",
    'Beyond Earth',
  ],
  feen1: [
    'Fables and Folk Tales',
    'Friendship',
    'Nurturing Nature',
    'Sports and Games',
    'Culture and Tradition',
  ],
  fess1: [
    'Locating Places on the Earth',
    'Oceans and Continents',
    'Landforms and Life',
    'Timeline and Sources of History',
    'India, That Is Bharat',
    'The Beginnings of Indian Civilisation',
    "India's Cultural Roots",
  ],
  fehn1: [
    'Baras Raha Hai Jal',
    'Har Ki Jeet',
    'Bansi Ki Dhun',
    'Meri Maa',
  ],
  fsk1: [
    'Prathama Patha: Mangalacharanam',
    'Dvitiya Patha: Parichaya',
    'Tritiya Patha: Subhashitani',
    'Chaturtha Patha: Vidyalaya',
  ],

  // --- CLASS 7 ---
  gemh1: [
    'Integers',
    'Fractions and Decimals',
    'Data Handling',
    'Simple Equations',
    'Lines and Angles',
    'The Triangle and its Properties',
    'Comparing Quantities',
    'Rational Numbers',
    'Perimeter and Area',
    'Algebraic Expressions',
    'Exponents and Powers',
    'Symmetry',
    'Visualising Solid Shapes',
  ],
  gecu1: [
    'The Ever-Evolving World of Science',
    'Exploring Substances: Acidic, Basic, and Neutral',
    'Electricity: Circuits and their Components',
    'The World of Metals and Non-metals',
    'Changes Around Us: Physical and Chemical',
    'Adolescence: A Stage of Growth and Change',
    'Heat Transfer in Nature',
    'Measurement of Time and Motion',
    'Life Processes in Animals',
    'Life Processes in Plants',
    'Light: Shadows and Reflections',
    'Earth, Moon, and the Sun',
  ],
  geen1: [
    'Three Questions',
    'A Gift of Chappals',
    'Gopal and the Hilsa Fish',
    'The Ashes That Made Trees Bloom',
    'Quality',
    'Expert Detectives',
    'The Invention of Vita-Wonk',
    'A Bicycle in Good Repair',
  ],
  gess1: [
    'Tracing Changes Through a Thousand Years',
    'New Kings and Kingdoms',
    'The Delhi Sultans',
    'The Mughal Empire',
    'Rulers and Buildings',
    'Towns, Traders and Craftspersons',
    'Tribes, Nomads and Settled Communities',
  ],

  // --- CLASS 8 (NCF-SE 2024 / Statutory Editions) ---
  hegp1: [
    'A Square and A Cube',
    'Power Play',
    'A Story of Numbers',
    'Quadrilaterals',
    'Number Play',
    'We Distribute, Yet Things Multiply',
    'Proportional Reasoning-1',
  ],
  hegp2: [
    'Fractions in Disguise',
    'The Baudhayana-Pythagoras Theorem',
    'Proportional Reasoning-2',
    'Exploring Some Geometric Themes',
    'Tales by Dots',
    'Algebra Play',
    'Area',
  ],
  hecu1: [
    'Exploring the Investigative World of Science',
    'The Invisible Living World: Beyond Our Naked Eye',
    'Health: The Ultimate Treasure',
    'Electricity: Magnetic and Heating Effects',
    'Exploring Forces',
    'Pressure, Winds, Storms, and Cyclones',
    'Particulate Nature of Matter',
    'Nature of Matter: Elements, Compounds, and Mixtures',
    'The Amazing World of Solutes, Solvents, and Solutions',
    'Light: Mirrors and Lenses',
    'Keeping Time with the Skies',
    'How Nature Works in Harmony',
    'Our Home: Earth, a Unique Life-Sustaining Planet',
  ],
  hehd1: [
    'The Best Christmas Present in the World',
    'The Tsunami',
    'Glimpses of the Past',
    "Bepin Choudhury's Lapse of Memory",
    'The Summit Within',
    "This is Jody's Fawn",
    'A Visit to Cambridge',
    'A Short Monsoon Diary',
  ],
  hess1: [
    'How, When and Where',
    'From Trade to Territory',
    'Ruling the Countryside',
    'Tribals, Dikus and the Vision of a Golden Age',
    'When People Rebel: 1857 and After',
    'Civilising the "Native", Educating the Nation',
  ],

  // --- CLASS 9 ---
  iemh1: [
    'Number Systems',
    'Polynomials',
    'Coordinate Geometry',
    'Linear Equations in Two Variables',
    "Introduction to Euclid's Geometry",
    'Lines and Angles',
    'Triangles',
    'Quadrilaterals',
    'Circles',
    "Heron's Formula",
    'Surface Areas and Volumes',
    'Statistics',
  ],
  iesc1: [
    'Matter in Our Surroundings',
    'Is Matter Around Us Pure',
    'Atoms and Molecules',
    'Structure of the Atom',
    'The Fundamental Unit of Life',
    'Tissues',
    'Motion',
    'Force and Laws of Motion',
    'Gravitation',
    'Work and Energy',
    'Sound',
    'Improvement in Food Resources',
  ],
  iebe1: [
    'How I Taught My Grandmother to Read',
    'The Pot Maker',
    'Winds of Change',
    'Vitamin-M',
    'The World of Limitless Possibilities',
    'Twin Melodies',
    'Carrier of Words',
    'Follow That Dream',
  ],
  iess1: [
    'The French Revolution',
    'Socialism in Europe and the Russian Revolution',
    'Nazism and the Rise of Hitler',
    'Forest Society and Colonialism',
    'Pastoralists in the Modern World',
    'India - Size and Location',
    'Physical Features of India',
    'Drainage',
    'Climate',
    'Natural Vegetation and Wild Life',
  ],
  ieks1: [
    'Do Bailon Ki Katha',
    'Lhasa Ki Aur',
    'Upbhoktavad Ki Sanskriti',
    'Sawle Sapno Ki Yaad',
  ],

  // --- CLASS 10 ---
  jemh1: [
    'Real Numbers',
    'Polynomials',
    'Pair of Linear Equations in Two Variables',
    'Quadratic Equations',
    'Arithmetic Progressions',
    'Triangles',
    'Coordinate Geometry',
    'Introduction to Trigonometry',
    'Some Applications of Trigonometry',
    'Circles',
    'Areas Related to Circles',
    'Surface Areas and Volumes',
    'Statistics',
    'Probability',
  ],
  jesc1: [
    'Chemical Reactions and Equations',
    'Acids, Bases and Salts',
    'Metals and Non-metals',
    'Carbon and its Compounds',
    'Life Processes',
    'Control and Coordination',
    'How do Organisms Reproduce?',
    'Heredity',
    'Light - Reflection and Refraction',
    'The Human Eye and the Colorful World',
    'Electricity',
    'Magnetic Effects of Electric Current',
    'Our Environment',
  ],
  jeff1: [
    'A Letter to God',
    'Nelson Mandela: Long Walk to Freedom',
    'Two Stories about Flying',
    'From the Diary of Anne Frank',
    'Glimpses of India',
    'Mijbil the Otter',
    'Madam Rides the Bus',
    'The Sermon at Benares',
    'The Proposal',
  ],
  jess1: [
    'The Rise of Nationalism in Europe',
    'Nationalism in India',
    'The Making of a Global World',
    'The Age of Industrialisation',
    'Print Culture and the Modern World',
    'Resources and Development',
    'Forest and Wildlife Resources',
    'Water Resources',
    'Agriculture',
    'Minerals and Energy Resources',
  ],
  jeks1: [
    'Netaji Ka Chashma',
    'Balgobin Bhagat',
    'Lakhnavi Andaz',
    'Ek Kahani Yeh Bhi',
  ],

  // --- CLASS 11 ---
  keph1: [
    'Units and Measurements',
    'Motion in a Straight Line',
    'Motion in a Plane',
    'Laws of Motion',
    'Work, Energy and Power',
    'System of Particles and Rotational Motion',
    'Gravitation',
    'Mechanical Properties of Solids',
    'Mechanical Properties of Fluids',
    'Thermal Properties of Matter',
    'Thermodynamics',
    'Kinetic Theory',
    'Oscillations',
    'Waves',
  ],
  kech1: [
    'Some Basic Concepts of Chemistry',
    'Structure of Atom',
    'Classification of Elements and Periodicity in Properties',
    'Chemical Bonding and Molecular Structure',
    'Chemical Thermodynamics',
    'Equilibrium',
    'Redox Reactions',
    'Organic Chemistry - Some Basic Principles and Techniques',
    'Hydrocarbons',
  ],
  kemh1: [
    'Sets',
    'Relations and Functions',
    'Trigonometric Functions',
    'Complex Numbers and Quadratic Equations',
    'Linear Inequalities',
    'Permutations and Combinations',
    'Binomial Theorem',
    'Sequences and Series',
    'Straight Lines',
    'Conic Sections',
    'Introduction to Three Dimensional Geometry',
    'Limits and Derivatives',
    'Statistics',
    'Probability',
  ],
  kebo1: [
    'The Living World',
    'Biological Classification',
    'Plant Kingdom',
    'Animal Kingdom',
    'Morphology of Flowering Plants',
    'Anatomy of Flowering Plants',
    'Structural Organisation in Animals',
    'Cell: The Unit of Life',
    'Biomolecules',
    'Cell Cycle and Cell Division',
  ],
  kecs1: [
    'Computer System Overview',
    'Data Representation',
    'Boolean Logic',
    'Introduction to Problem Solving',
    'Getting Started with Python',
    'Python Fundamentals',
    'Data Handling in Python',
    'Flow of Control',
  ],
  kehb1: [
    'The Portrait of a Lady',
    "We're Not Afraid to Die... if We Can All Be Together",
    'Discovering Tut: the Saga Continues',
    'The Laburnum Top (Poem)',
    'The Voice of the Rain (Poem)',
    'Childhood (Poem)',
    'The Adventure',
    'Silk Road',
  ],
  keac1: [
    'Introduction to Accounting',
    'Theory Base of Accounting',
    'Recording of Transactions - I',
    'Recording of Transactions - II',
    'Bank Reconciliation Statement',
    'Trial Balance and Rectification of Errors',
    'Depreciation, Provisions and Reserves',
    'Financial Statements - I',
  ],
  kebs1: [
    'Evolution and Fundamentals of Business',
    'Forms of Business Organisations',
    'Public, Private and Global Enterprises',
    'Business Services',
    'Emerging Modes of Business',
    'Social Responsibilities of Business and Business Ethics',
  ],
  keec1: [
    'Introduction to Statistics',
    'Collection of Data',
    'Organisation of Data',
    'Presentation of Data',
    'Measures of Central Tendency',
    'Correlation',
  ],
  kest1: [
    'Writing and City Life (Mesopotamia)',
    'An Empire Across Three Continents (Roman Empire)',
    'Nomadic Empires (Mongols)',
    'The Three Orders (Feudal Europe)',
    'Changing Cultural Traditions (Renaissance)',
  ],
  keps1: [
    'Constitution: Why and How?',
    'Rights in the Indian Constitution',
    'Election and Representation',
    'Executive',
    'Legislature',
    'Judiciary',
  ],
  kegy1: [
    'Geography as a Discipline',
    'The Origin and Evolution of the Earth',
    'Interior of the Earth',
    'Distribution of Oceans and Continents',
    'Geomorphic Processes',
  ],

  // --- CLASS 12 ---
  leph1: [
    'Electric Charges and Fields',
    'Electrostatic Potential and Capacitance',
    'Current Electricity',
    'Moving Charges and Magnetism',
    'Magnetism and Matter',
    'Electromagnetic Induction',
    'Alternating Current',
    'Electromagnetic Waves',
    'Ray Optics and Optical Instruments',
    'Wave Optics',
    'Dual Nature of Radiation and Matter',
    'Atoms',
    'Nuclei',
    'Semiconductor Electronics: Materials, Devices and Simple Circuits',
  ],
  lech1: [
    'Solutions',
    'Electrochemistry',
    'Chemical Kinetics',
    'The d- and f- Block Elements',
    'Coordination Compounds',
    'Haloalkanes and Haloarenes',
    'Alcohols, Phenols and Ethers',
    'Aldehydes, Ketones and Carboxylic Acids',
    'Amines',
    'Biomolecules',
  ],
  lemh1: [
    'Relations and Functions',
    'Inverse Trigonometric Functions',
    'Matrices',
    'Determinants',
    'Continuity and Differentiability',
    'Application of Derivatives',
    'Integrals',
    'Application of Integrals',
    'Differential Equations',
    'Vector Algebra',
    'Three Dimensional Geometry',
    'Linear Programming',
    'Probability',
  ],
  lebo1: [
    'Sexual Reproduction in Flowering Plants',
    'Human Reproduction',
    'Reproductive Health',
    'Principles of Inheritance and Variation',
    'Molecular Basis of Inheritance',
    'Evolution',
    'Human Health and Disease',
    'Microbes in Human Welfare',
    'Biotechnology: Principles and Processes',
    'Biotechnology and its Applications',
    'Organisms and Populations',
    'Ecosystem',
    'Biodiversity and Conservation',
  ],
  lecs1: [
    'Python Revision Tour',
    'Functions in Python',
    'Using Python Libraries',
    'File Handling in Python',
    'Recursion',
    'Idea of Efficiency',
    'Data Structures (Stacks & Queues)',
  ],
  lefl1: [
    'The Last Lesson',
    'Lost Spring',
    'Deep Water',
    'The Rattrap',
    'Indigo',
    'Poets and Pancakes',
    'The Interview',
    'Going Places',
  ],
  leac1: [
    'Accounting for Partnership: Basic Concepts',
    'Reconstitution of a Partnership Firm - Admission of a Partner',
    'Reconstitution of a Partnership Firm - Retirement/Death of a Partner',
    'Dissolution of a Partnership Firm',
    'Accounting for Share Capital',
    'Issue and Redemption of Debentures',
    'Financial Statements of a Company',
    'Analysis of Financial Statements',
  ],
  lebs1: [
    'Nature and Significance of Management',
    'Principles of Management',
    'Business Environment',
    'Planning',
    'Organising',
    'Staffing',
    'Directing',
    'Controlling',
    'Financial Management',
    'Financial Markets',
    'Marketing',
    'Consumer Protection',
  ],
  leec1: [
    'Introduction to Macroeconomics',
    'National Income Accounting',
    'Money and Banking',
    'Determination of Income and Employment',
    'Government Budget and the Economy',
    'Open Economy Macroeconomics',
    'Development Experience (1947-90) and Economic Reforms since 1991',
    'Current Challenges Facing the Indian Economy',
  ],
  lest1: [
    'Bricks, Beads and Bones (Harappan Civilisation)',
    'Kings, Farmers and Towns (Early States and Economies)',
    'Kinship, Caste and Class (Early Societies)',
    'Thinkers, Beliefs and Buildings (Cultural Developments)',
    'Through the Eyes of Travellers (Perceptions of Society)',
    'Bhakti-Sufi Traditions (Religious Beliefs and Texts)',
  ],
  leps1: [
    'The End of Bipolarity',
    'Contemporary Centres of Power',
    'Contemporary South Asia',
    'International Organisations',
    'Security in the Contemporary World',
    'Environment and Natural Resources',
  ],
  legy1: [
    'Human Geography: Nature and Scope',
    'The World Population: Distribution, Density and Growth',
    'Human Development',
    'Primary Activities',
    'Secondary Activities',
    'Tertiary and Quaternary Activities',
  ],
};

/**
 * Extracts and returns the official Table of Contents for a given manifest entry.
 * Fails closed with 'PENDING_VERIFICATION' and [] chapters if the official source
 * is unverified or unavailable.
 */
export async function extractOfficialTextbookToc(
  entry: CbseSourceManifestEntry
): Promise<OfficialExtractedTextbook> {
  // Fail-closed check
  if (entry.verification_status !== 'VERIFIED' || !entry.official_source_code || entry.official_source_code === 'UNASSIGNED') {
    return {
      textbook_id: entry.textbook_id,
      official_code: entry.official_source_code,
      official_title: entry.official_textbook_name,
      grade_level: entry.grade_level,
      subject_id: entry.subject_id,
      curriculum_version_id: entry.curriculum_version_id,
      stream_id: entry.stream_id,
      part_volume: entry.part_volume,
      chapters: [],
      source_url: entry.official_source_url,
      verification_status: 'PENDING_VERIFICATION',
    };
  }

  const rawTitles = STATUTORY_NCERT_ORACLE_TOC[entry.official_source_code];
  if (!rawTitles || rawTitles.length === 0) {
    return {
      textbook_id: entry.textbook_id,
      official_code: entry.official_source_code,
      official_title: entry.official_textbook_name,
      grade_level: entry.grade_level,
      subject_id: entry.subject_id,
      curriculum_version_id: entry.curriculum_version_id,
      stream_id: entry.stream_id,
      part_volume: entry.part_volume,
      chapters: [],
      source_url: entry.official_source_url,
      verification_status: 'PENDING_VERIFICATION',
    };
  }

  const chapters: OfficialExtractedChapter[] = rawTitles.map((title, idx) => {
    const order = idx + 1;
    return {
      chapter_number: order,
      chapter_title: normalizeChapterTitle(title),
      official_sequence_order: order,
      part_volume: entry.part_volume || null,
      description: `Official Chapter ${order}: ${normalizeChapterTitle(title)} from ${entry.official_textbook_name}`,
      sections_available: true,
    };
  });

  return {
    textbook_id: entry.textbook_id,
    official_code: entry.official_source_code,
    official_title: entry.official_textbook_name,
    grade_level: entry.grade_level,
    subject_id: entry.subject_id,
    curriculum_version_id: entry.curriculum_version_id,
    stream_id: entry.stream_id,
    part_volume: entry.part_volume,
    chapters,
    source_url: entry.official_source_url,
    verification_status: 'VERIFIED',
  };
}
